"""Python classes representing Qt widgets, generated by pyside-uic

Do not modify these file sdirectly
Use generate_components.sh to generate classes from all templates
located in gui/ui_component_templates directory
"""
